name: Lighthouse CI

on: 
  deployment_status:

jobs:
  lhci:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun
        env:
          DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}
          TEST_LOGIN_PATH: /api/auth/signin
          TEST_USER: django
          TEST_PASSWORD: password
          LHCI_CHROME_PATH: /opt/hostedtoolcache/chromium/latest/x64/chrome
